### ISSUE TITLE
[Feature Request] Translate button

### ISSUE THREAD

**Issue by joelemanoel** [jefelewis/react-native-ultimate-modal-picker#10]
Hi,

I request option to translate button Cancel and Done in iOS.

**Comment by jefelewis** [comment]
@joelemanoel 
Sorry for the delayed response! It's been a busy year and I just haven't had the time to maintain some of my libraries. However, I've taken the past week and revamped the library completely with custom styles, React 17, iOS 14 support, improved `darkMode`, updated dependencies, improved `package.json`, improved file organization and file names, and Typescript Improvements. 

In version `1.1.0`, I've added the optional props `cancelText` and `doneText` that allow you to pass any string as either buttons. I wanted to keep this library lightweight and I didn't want to add additional libraries, so this seemed to be the best route to go. Best of luck with your project!
