### ISSUE TITLE
DatePicker is not working

### ISSUE THREAD

**Issue by tnstjddlrl** [jefelewis/react-native-ultimate-modal-picker#11]
what is this? how to fix

<DatePicker
        title="Date"
        onChange={(date) => console.log(date)}
        mode="calendar"
      />
![image](https://user-images.githubusercontent.com/48933775/103517740-f916cc00-4eb5-11eb-96a6-fa0d84dec896.png)

**Comment by jefelewis** [comment]
@tnstjddlrl Sorry for the delayed response! It's been a busy year and I just haven't had the time to maintain some of my libraries. However, I've taken the past week and revamped the library completely with custom styles, React 17, iOS 14 support, improved `darkMode`, updated dependencies, improved `package.json`, improved file organization and file names, and Typescript Improvements. 

If this issue still persists, let me know so I can fix it. If it's fixed, I'll close out the issue.
