### ISSUE TITLE
Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from \'@react-native-community/picker\' instead of \'react-native\'.

### ISSUE THREAD

**Issue by Trazmor** [jefelewis/react-native-ultimate-modal-picker#4]
I got this message using ListPicker :
`Warning: Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from \'@react-native-community/picker\' instead of \'react-native\'.`

Maybe we just have to change the dependencies, I'll try later

React-Native v0.62

**Comment by jefelewis** [comment]
Trazmor,

That's just a warning from React Native. I believe it's unrelated to the dependency. The React team is just warning users to use the dependency `@react-native-community/picker` instead of it being built into React Native. `@react-native-community/picker` is what my library uses.
