### ISSUE TITLE
Can't live in the same project with react-native-modal-datetime-picker

### ISSUE THREAD

**Issue by IlyaSemenov** [jefelewis/react-native-ultimate-modal-picker#8]
If a project imports two modules:

```
import DateTimePickerModal from "react-native-modal-datetime-picker"
import { ListPicker } from "react-native-ultimate-modal-picker"
```

it crashes:

<img width="559" alt="Screenshot 2020-09-29 at 13 05 03" src="https://user-images.githubusercontent.com/128121/94519106-6b8f6480-0254-11eb-9de6-430e1ab438d6.png">

Expected: the two modules live happily alongside each other.

**Comment by jefelewis** [comment]
@IlyaSemenov Sorry for the delayed response! It's been a busy year and I just haven't had the time to maintain some of my libraries. However, I've taken the past week and revamped the library completely with custom styles, React 17, iOS 14 support, improved `darkMode`, updated dependencies, improved `package.json`, improved file organization and file names, and Typescript Improvements. 

If this issue still persists, let me know so I can fix it. If it's fixed, I'll close out the issue.
